# Generated by Django 4.1 on 2022-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
