# Generated by Django 4.1 on 2022-10-11 18:02

from django.db import migrations
from django.db.models import Q


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    group = Group.objects.create(
       name="Photographer",
    )

    permissions = Permission.objects.filter(Q(codename__icontains="category") | Q(codename__icontains="photo"))

    for permission in permissions:
        group.permissions.add(permission)
    group.save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            "Photographer",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_visible_photo_description_photo_visible'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
