version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nicolamorandi
      POSTGRES_USER: nicolamorandi
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  backend:
    build: ../backend
    restart: unless-stopped
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost
      - HOST=*
      - DATABASE_URL=psql://nicolamorandi:password@db/nicolamorandi
      - SECRET_KEY=qqm2xhl&11+eoovkl_p8#d+@0&mjp4!5g8vn5q#z)8p52wudnf
      - DEBUG=False
    depends_on:
      - db
    volumes:
      - backend_media:/usr/src/app/media
      - backend_static:/usr/src/app/static
      - backend_logs:/usr/src/app/logs

  backend-nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ../backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_media:/mediafiles
      - backend_static:/staticfiles
    depends_on:
      - backend
    ports:
      - 8201:80

  frontend:
    build: ../frontend
    restart: unless-stopped
    ports:
      - 8200:80

volumes:
  postgres_data:
  backend_media:
  backend_static:
  backend_logs: