version: '3'
services:
  frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    networks:
      - default
      - traefik-network
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.nicolamorandi-testing.rule=Host(`nicolamorandi.testing.morandizzi.com`)"
      - "traefik.http.routers.nicolamorandi-testing.entrypoints=websecure"
      - "traefik.http.routers.nicolamorandi-testing.tls=true"
      - "traefik.http.routers.nicolamorandi-testing.service=nicolamorandi-testing"
      - "traefik.http.services.nicolamorandi-testing.loadbalancer.server.port=80"
      - "traefik.http.routers.nicolamorandi-testing.tls.certresolver=le"
      - "traefik.http.routers.nicolamorandi-testing.tls.domains[0].main=nicolamorandi.testing.morandizzi.com"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nicolamorandi-testing.middlewares=redirect-to-https@docker"

  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    environment:
      - CORS_ALLOWED_ORIGINS=https://nicolamorandi.testing.morandizzi.com
      - CSRF_TRUSTED_ORIGINS=https://nicolamorandi.testing.morandizzi.com
      - HOST=https://nicolamorandi.testing.morandizzi.com
      - DATABASE_URL=psql://nicolamorandi:${DATABASE_PASSWORD}@db/nicolamorandi
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=True
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 5 --timeout 120
    depends_on:
      - db
    volumes:
      - backend_media:/usr/src/app/media
      - backend_static:/usr/src/app/static
      - backend_logs:/usr/src/app/logs

  backend-nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ../backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_media:/mediafiles
      - backend_static:/staticfiles
    depends_on:
      - backend
    networks:
      - default
      - traefik-network
    labels:
      # Backend
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.nicolamorandi-testing-backend.rule=Host(`nicolamorandi.testing.morandizzi.com`) && (PathPrefix(`/admin`) || PathPrefix(`/api`) || PathPrefix(`/static`)  || PathPrefix(`/media`))"
      - "traefik.http.routers.nicolamorandi-testing-backend.entrypoints=websecure"
      - "traefik.http.routers.nicolamorandi-testing-backend.tls=true"
      - "traefik.http.routers.nicolamorandi-testing-backend.service=nicolamorandi-testing-backend"
      - "traefik.http.services.nicolamorandi-testing-backend.loadbalancer.server.port=80"
      - "traefik.http.routers.nicolamorandi-testing-backend.tls.certresolver=le"
      - "traefik.http.routers.nicolamorandi-testing-backend.tls.domains[0].main=nicolamorandi.testing.morandizzi.com"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nicolamorandi-testing-backend.middlewares=redirect-to-https@docker"

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nicolamorandi
      POSTGRES_USER: nicolamorandi
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

networks:
  traefik-network:
    external: true

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nicolamorandi/testing/postgres

  backend_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nicolamorandi/testing/media

  backend_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nicolamorandi/testing/static

  backend_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nicolamorandi/testing/logs

