version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nicolamorandi
      POSTGRES_USER: nicolamorandi
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  postgres_data:
