name: Create Release Workflow

run-name: ${{ github.actor }} run the create release workflow

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit

  django-build-production:
    needs: [common]
    uses: artur094/workflows/.github/workflows/django-build-push.yml@main
    with:
      #LABELS: "['pipeline', 'native', 'raspberry']"
      LABELS: "['ubuntu-latest']"
      DOCKER_IMAGE: backend
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
      DOCKERFILE_PATH: Dockerfile
      WORKING_DIRECTORY: backend
    secrets: inherit

  angular-build-production:
    needs: [common]
    uses: artur094/workflows/.github/workflows/angular-build-push.yml@main
    with:
      #LABELS: "['pipeline', 'native', 'raspberry']"
      LABELS: "['ubuntu-latest']"
      DOCKER_IMAGE: frontend
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
      DOCKERFILE_PATH: Dockerfile
      WORKING_DIRECTORY: frontend
      ENVIRONMENT: production
      NODE_VERSION: 16.17.0
    secrets: inherit

  deploy:
    needs: [django-build-production, angular-build-production]
    uses: artur094/workflows/.github/workflows/docker-deploy.yml@main
    with:
      LABELS: "['native', 'contabo', 'deploy']"
      DOCKER_COMPOSE_FILE: docker/docker-compose.prod.yml
      PROJECT_NAME: nik-morandi-photo-gallery-production
      ENVIRONMENT: production
      IMAGE_NAMES: "{
        'FRONTEND_IMAGE': 'ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}',
        'BACKEND_IMAGE': 'ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}'
      }"
    secrets: inherit
