name: Common Verify Code Workflow
run-name: ${{ github.actor }} run the verify workflow

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit