name: Main Workflow

run-name: ${{ github.actor }} run the main workflow

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit

  django-build-testing:
    needs: [common]
    uses: artur094/workflows/.github/workflows/django-build-push.yml@main
    with:
      #LABELS: "['pipeline', 'native', 'raspberry']"
      LABELS: "['ubuntu-latest']"
      DOCKER_IMAGE: backend
      DOCKER_IMAGE_TAG: latest
      DOCKERFILE_PATH: Dockerfile
      WORKING_DIRECTORY: backend
    secrets: inherit

  angular-build-testing:
    needs: [common]
    uses: artur094/workflows/.github/workflows/angular-build-push.yml@main
    with:
      #LABELS: "['pipeline', 'native', 'raspberry']"
      LABELS: "['ubuntu-latest']"
      DOCKER_IMAGE: frontend
      DOCKER_IMAGE_TAG: latest
      DOCKERFILE_PATH: Dockerfile
      WORKING_DIRECTORY: frontend
      ENVIRONMENT: testing
      NODE_VERSION: 16.17.0
    secrets: inherit

  deploy:
    needs: [angular-build-testing, django-build-testing]
    uses: artur094/workflows/.github/workflows/docker-deploy.yml@main
    with:
      LABELS: "['native', 'raspberry', 'deploy']"
      DOCKER_COMPOSE_FILE: docker/docker-compose.testing.yml
      PROJECT_NAME: nik-morandi-photo-gallery-production
      ENVIRONMENT: testing
      IMAGE_NAMES: "{
        'FRONTEND_IMAGE': 'ghcr.io/${{ github.repository}}/frontend:latest',
        'BACKEND_IMAGE': 'ghcr.io/${{ github.repository}}/backend:latest'
      }"
    secrets: inherit