name: Common Verify Code Workflow
run-name: ${{ github.actor }} run the verify workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit