name: Deploy Testing Workflow

run-name: ${{ github.actor }} run the deploy to testing workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: artur094/workflows/.github/workflows/docker-deploy.yml@main
    with:
      LABELS: "['native', 'raspberry', 'deploy']"
      DOCKER_COMPOSE_FILE: docker/docker-compose.testing.yml
      PROJECT_NAME: nik-morandi-photo-gallery-testing
      ENVIRONMENT: testing
      IMAGE_NAMES: "{
        'FRONTEND_IMAGE': 'ghcr.io/${{ github.repository}}/frontend:latest',
        'BACKEND_IMAGE': 'ghcr.io/${{ github.repository}}/backend:latest'
      }"
    secrets: inherit