on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/docker-deploy.yml
    with:
      LABELS: "['native', 'raspberry', 'deploy']"
      DOCKER_COMPOSE_FILE: docker/docker-compose.testing.yml
      PROJECT_NAME: nik-morandi-photo-gallery
      IMAGE_NAMES: "{
        'FRONTEND_IMAGE': 'ghcr.io/${{ github.repository}}/frontend:latest',
        'BACKEND_IMAGE': 'ghcr.io/${{ github.repository}}/backend:latest'
      }"
      WORKING_DIRECTORY: frontend
    secrets: inherit