name: Deploy Production Workflow

run-name: ${{ github.actor }} run the deploy to production workflow

on:
  workflow_dispatch:
    inputs:
      TAG:
        type: string
        description: Tag to deploy
jobs:
  deploy:
    uses: artur094/workflows/.github/workflows/docker-deploy.yml@main
    with:
      LABELS: "['native', 'contabo', 'deploy']"
      DOCKER_COMPOSE_FILE: docker/docker-compose.prod.yml
      PROJECT_NAME: nik-morandi-photo-gallery-production
      ENVIRONMENT: production
      IMAGE_NAMES: "{
        'FRONTEND_IMAGE': 'ghcr.io/${{ github.repository }}/frontend:${{ github.event.inputs.TAG }}',
        'BACKEND_IMAGE': 'ghcr.io/${{ github.repository }}/backend:${{ github.event.inputs.TAG }}'
      }"
    secrets: inherit
