name: Common Verify Code Workflow
run-name: ${{ github.actor }} run the verify workflow

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  common:
#    uses: ./.github/workflows/common.yml
#    secrets: inherit

  # Move all next steps to default-branch
  django-build-testing:
    uses: ./.github/workflows/django-build-push.yml
    with:
      LABELS: "['pipeline', 'native', 'raspberry']"
      DOCKER_IMAGE: backend
      DOCKER_IMAGE_TAG: latest
      DOCKERFILE_PATH: Dockerfile
      WORKING_DIRECTORY: backend
    secrets: inherit

#  angular-build-testing:
#    uses: ./.github/workflows/angular-build-push.yml
#    with:
#      LABELS: "['pipeline', 'native', 'raspberry']"
#      DOCKER_IMAGE: frontend
#      DOCKER_IMAGE_TAG: latest
#      DOCKERFILE_PATH: Dockerfile
#      WORKING_DIRECTORY: frontend
#      ENVIRONMENT: testing
#      NODE_VERSION: 18.4.0
#    secrets: inherit