name: Pull Request Workflow

run-name: ${{ github.actor }} run the PR workflow

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit